"""Add feedback relationship to User model

Revision ID: 8467f11e4f53
Revises: 58de2cd315dc
Create Date: 2025-07-18 23:07:03.218325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8467f11e4f53'
down_revision: Union[str, None] = '58de2cd315dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
