"""add organization_name to user

Revision ID: cd86b4256628
Revises: 8467f11e4f53
Create Date: 2025-07-22 17:06:05.768584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd86b4256628'
down_revision: Union[str, None] = '8467f11e4f53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organization_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'organization_name')
    # ### end Alembic commands ###
