"""Add feedback relationship to User model

Revision ID: e5daa2c7261d
Revises: 3bdcc269ee28
Create Date: 2025-07-17 01:46:00.795405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5daa2c7261d'
down_revision: Union[str, None] = '3bdcc269ee28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
