"""Add relationships between User, Session and Message

Revision ID: ee5e4c8c5131
Revises: 
Create Date: 2025-07-16 11:20:01.020943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee5e4c8c5131'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('registration_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registration_date')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_column('messages', 'user_id')
    # ### end Alembic commands ###
